import argparse
import csv
import json


def import_authors(csv_filepath):
    authors = []

    with open(csv_filepath, "r") as csv_file:
        reader = csv.DictReader(csv_file)

        for row in reader:
            authors.append(row)

    return authors


def output_author_bank(comment_categories, output_filepath):
    with open(output_filepath, "w") as output_file:
        json.dump(comment_categories, output_file, indent=4)


def main(csv_filepath, output_filepath):
    authors = import_authors(csv_filepath)
    output_author_bank(authors, output_filepath)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        "Script to import emulator author bank data from CSV generated by google sheet into post data JSON format."
    )
    parser.add_argument(
        "csv_file",
        help="The csv file to import from",
    )
    parser.add_argument(
        "output_file",
        help="The name of the output JSON file to export to",
    )

    args = parser.parse_args()
    main(args.csv_file, args.output_file)
