import argparse
import csv
import json


def import_categories(csv_filepath):
    comment_categories = {}

    with open(csv_filepath, "r") as csv_file:
        reader = csv.DictReader(csv_file)

        for row in reader:
            if "category" not in row:
                print("row {0} does not have a category assignment, putting in general".format(row))
                row["category"] = "general"

            category = row["category"]
            comments = comment_categories.get(category, [])
            comments.append(row)
            comment_categories[category] = comments

    return comment_categories


def output_comment_bank(comment_categories, output_filepath):
    with open(output_filepath, "w") as output_file:
        json.dump(comment_categories, output_file, indent=4)


def main(csv_filepath, output_filepath):
    comment_categories = import_categories(csv_filepath)
    output_comment_bank(comment_categories, output_filepath)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        "Script to import emulator comment data from CSV generated by google sheet into post data JSON format."
    )
    parser.add_argument(
        "csv_file",
        help="The csv file to import from",
    )
    parser.add_argument(
        "output_file",
        help="The name of the output JSON file to export to",
    )

    args = parser.parse_args()
    main(args.csv_file, args.output_file)
